/**
 * Phase 5 benchmark: Identifier → index lookup, linear scan vs hashmap.
 *
 * Builds a 10,000+ character document, then measures repeated lookups of the
 * same Identifier set. The linear baseline mirrors the pre-Phase-5 findIndex;
 * the hashmap path is RGA.lookupIndex (backed by indexById).
 *
 * Run: pnpm --filter @collabtext/crdt bench
 */

import { Bench } from "tinybench";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { RGA } from "../src/RGA.js";
import type { Identifier, RGANode } from "../src/types.js";
import { identifiersEqual } from "../src/types.js";

const DOC_SIZE = 12_000;
const LOOKUPS_PER_ITER = 2_000;

/** Pre-Phase-5 O(n) scan — kept here only as a benchmark baseline. */
function linearScanLookup(nodes: readonly RGANode[], id: Identifier): number {
  for (let i = 0; i < nodes.length; i += 1) {
    const node = nodes[i];
    if (node && identifiersEqual(node.id, id)) {
      return i;
    }
  }
  return -1;
}

function buildDocument(size: number): { rga: RGA; sampleIds: Identifier[] } {
  const rga = new RGA("bench");
  const sampleIds: Identifier[] = [];
  let prev: Identifier | null = null;
  for (let i = 0; i < size; i += 1) {
    const char = String.fromCharCode(97 + (i % 26));
    const op = rga.insert(prev, char);
    prev = op.id;
    // Sample evenly across the document for representative lookups.
    if (i % Math.floor(size / 50) === 0) {
      sampleIds.push(op.id);
    }
  }
  // Also include near-end ids (worst case for linear scan).
  const nodes = rga.getNodes();
  sampleIds.push(nodes[nodes.length - 1]!.id);
  sampleIds.push(nodes[Math.floor(nodes.length * 0.9)]!.id);
  return { rga, sampleIds };
}

async function main(): Promise<void> {
  const { rga, sampleIds } = buildDocument(DOC_SIZE);
  const nodes = rga.getNodes();
  expectConsistent(rga, sampleIds);

  let sampleCursor = 0;
  const nextId = (): Identifier => {
    const id = sampleIds[sampleCursor % sampleIds.length]!;
    sampleCursor += 1;
    return id;
  };

  const bench = new Bench({ time: 800, warmupTime: 200 });

  bench
    .add("linear-scan lookup (pre-Phase-5)", () => {
      for (let i = 0; i < LOOKUPS_PER_ITER; i += 1) {
        linearScanLookup(nodes, nextId());
      }
    })
    .add("hashmap lookup (Phase-5 indexById)", () => {
      for (let i = 0; i < LOOKUPS_PER_ITER; i += 1) {
        rga.lookupIndex(nextId());
      }
    });

  await bench.run();

  const results = bench.table();
  console.table(results);

  const linear = bench.tasks.find((t) => t.name.includes("linear-scan"));
  const hashed = bench.tasks.find((t) => t.name.includes("hashmap"));
  const linearHz = linear?.result?.hz ?? 0;
  const hashedHz = hashed?.result?.hz ?? 0;
  const speedup = linearHz > 0 ? hashedHz / linearHz : 0;

  const linearNs =
    linear?.result?.mean !== undefined ? linear.result.mean * 1e6 : 0;
  const hashedNs =
    hashed?.result?.mean !== undefined ? hashed.result.mean * 1e6 : 0;

  const markdown = `# RGA lookup benchmark results

Generated by \`pnpm --filter @collabtext/crdt bench\` on ${new Date().toISOString()}.

## Setup

- Document size: **${DOC_SIZE.toLocaleString()}** characters (all live; no tombstones)
- Each benchmark iteration performs **${LOOKUPS_PER_ITER.toLocaleString()}** Identifier → index lookups
- Sample ids are spread across the document, including near-end positions (worst case for linear scan)
- Tooling: [tinybench](https://github.com/tinylibs/tinybench)

## Results

| Approach | Mean time / iter | Ops/sec (hz) |
|----------|------------------|--------------|
| Linear scan (pre-Phase-5 \`findIndex\`) | ${linearNs.toFixed(2)} ns | ${linearHz.toFixed(2)} |
| Hashmap \`indexById\` (Phase 5) | ${hashedNs.toFixed(2)} ns | ${hashedHz.toFixed(2)} |

**Speedup (hashmap vs linear):** ~**${speedup.toFixed(1)}×** more iterations per second for Identifier lookup.

> Note: each "iteration" above is a batch of ${LOOKUPS_PER_ITER} lookups. Absolute ns values are batch means from tinybench; the ratio is what matters for the optimization claim.

## Interpretation

Phase 5 replaced O(n) \`findIndex\` walks with an \`Identifier → index\` map maintained on insert. Lookups used by \`insert\` (resolve \`leftOrigin\`) and \`delete\` (resolve \`targetId\`) are now O(1).

## Next bottleneck at larger scale

Lookup is no longer the hot path. Remaining O(n) costs per insert:

1. **\`Array.splice\`** to place the new node in the sequence array
2. **Index-map shift** — every map entry at or after the splice point is incremented
3. **Walk-right** among concurrent siblings (usually short; worst-case O(n))

At hundreds of thousands of characters, a tree-backed sequence (e.g. a balanced binary tree or rope keyed by Identifier order) would make both placement and index maintenance logarithmic. Tombstone GC would also matter once deleted nodes dominate memory.
`;

  const repoDocs = join(
    dirname(fileURLToPath(import.meta.url)),
    "../../../docs/benchmark-results.md",
  );
  writeFileSync(repoDocs, markdown, "utf8");
  console.log(`\nWrote ${repoDocs}`);
  console.log(`Approximate lookup speedup: ${speedup.toFixed(1)}×`);
}

function expectConsistent(rga: RGA, sampleIds: Identifier[]): void {
  for (const id of sampleIds) {
    const mapped = rga.lookupIndex(id);
    const linear = linearScanLookup(rga.getNodes(), id);
    if (mapped !== linear) {
      throw new Error(`index mismatch for ${id.timestamp}:${id.clientId}`);
    }
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
